language: ruby
rvm:
  - 2.2.3
before_install:
  - sudo apt-get install libqtwebkit-dev
  - sudo apt-get install xvfb
  - sudo apt-get install imagemagick
  - sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-proper -y
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update
  - sudo apt-get install qtcreator libqtwebkit-dev qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - bundle install
  - bundle exec rake db:migrate db:seed db:test:prepare
  - bundle exec rake cucumber
  - bundle exec rake spec
notifications:
  email: false



